server:
   port: 8080
   tomcat:
      basedir: ${application.home}
      max-threads: 200
      access-log-enabled: true
      access-log-pattern: "%t lbip=%h identd=%l user=%u status=%s method=%m url=%U bytes=%b duration=%D"
   ssl:
       enabled: false
   compression:
       enabled: false
       min-response-size: 1024
       mime-types: "application/json"